site_name: Capital Nexus

repo_name: "2025.1-T01-CapitalNexus"
repo_url: https://github.com/mdsreq-fga-unb/2025.1-T01-CapitalNexus

nav:
  - Início: index.md
  - Visão do Produto e Projeto:
      - Cenário atual do cliente e do negócio: visao/cenario.md
      - Solução proposta: visao/solucao.md
      - Estratégias de engenharia de software: visao/estrategias.md
      - Engenharia de requisitos: visao/engrequisitos.md
      - Cronograma: visao/cronograma.md
      - Interação entre equipe e cliente: visao/interacao.md
      - DoR e DoD: visao/doredod.md
      - Evidências: visao/Evidências.md
      - Lições aprendidas: visao/licoes.md
      - Política de contribuição: visao/contribuicao.md
      - Referências: visao/referencias.md 
  - Requisitos:
      - Requisitos funcionais: requisitos/reqfuncional.md
      - Requisitos não funcionais: requisitos/reqnaofuncional.md
  - Backlog:
      - Backlog Geral: backlog/geral.md
      - Priorização e Produto Mínimo Viável: backlog/mvp.md
  - Entregas:
      - Unidade 1: entregas/unidadeum.md
      - Unidade 2: entregas/unidade2.md
      - Unidade 3: 
        - PBB: entregas/unidade3/PBB.md
        - USM: entregas/unidade3/USM.md
        - Apresentação e incremento: entregas/unidade3/entrega.md
      - Unidade 4:
        - Casos de uso: entregas/unidade4/casosdeuso.md


theme:
  name: material
  language: pt-BR

  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - content.code.select
    - content.code.copy


  palette:
    - scheme: default
      primary: "purple"
      accent: "purple"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - scheme: slate
      primary: "purple"
      accent: "purple"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  logo:
  favicon:
  highlightjs: true

extra_css:
  - stylesheets/styles.css

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
