# Generated by Django 5.2 on 2025-06-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumo', models.TextField(help_text='Projeto desenvolvido de x - x, para participar ... e validar x.')),
                ('imagem', models.ImageField(upload_to='project_images/')),
                ('dimensoes', models.TextField(help_text='Foguete para 1km de apogeu, com 2.13m de comprimento, 15.5cm de diâmetro e 28kg.')),
                ('situacao', models.TextField(help_text='Lançado em 2022 na LASC, conseguindo o 1° lugar em 2022.')),
                ('custo', models.TextField(help_text='O custo foi de R$XX.XXX,XX')),
            ],
        ),
    ]
