# Generated by Django 5.2 on 2025-06-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_mensagemcontato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='project_images/')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
            },
        ),
    ]
