# Generated by Django 5.2 on 2025-05-18 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('matricula', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Nucleo',
            fields=[
                ('nome', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='MembroNucleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.cargo')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membro')),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.nucleo')),
            ],
            options={
                'unique_together': {('membro', 'nucleo')},
            },
        ),
    ]
