# Generated by Django 5.2 on 2025-07-11 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Nucleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('categoria', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Núcleo',
                'verbose_name_plural': 'Núcleos',
            },
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('RG', 'Reunião Geral'), ('PC', 'Ponto de controle')], default='PC', max_length=2)),
                ('ata', models.FileField(blank=True, null=True, upload_to='atas/')),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_justificativa', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status_analise', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=20)),
                ('feedback_analise', models.TextField(blank=True, help_text='Feedback do Núcleo X sobre a análise.', null=True)),
                ('falta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.falta')),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('matricula', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='falta',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membro'),
        ),
        migrations.AddField(
            model_name='falta',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.reuniao'),
        ),
        migrations.CreateModel(
            name='Advertencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membro')),
            ],
            options={
                'unique_together': {('membro', 'id')},
            },
        ),
        migrations.CreateModel(
            name='MembroNucleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.cargo')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membro')),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.nucleo')),
            ],
            options={
                'verbose_name': 'Associação',
                'verbose_name_plural': 'Associações',
                'unique_together': {('membro', 'nucleo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='falta',
            unique_together={('membro', 'reuniao')},
        ),
    ]
