# Generated by Django 5.2 on 2025-06-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membronucleo',
            options={'verbose_name': 'Associação', 'verbose_name_plural': 'Associações'},
        ),
        migrations.AlterModelOptions(
            name='nucleo',
            options={'verbose_name': 'Núcleo', 'verbose_name_plural': 'Núcleos'},
        ),
    ]
