# Generated by Django 5.2 on 2025-07-13 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('EQUIPAMENTO', 'Equipamento'), ('CONSUMIVEL', 'Consumível'), ('ELETRONICO', 'Eletrônico'), ('OUTRO', 'Outro')], max_length=20)),
                ('finalidade', models.CharField(max_length=200)),
                ('quantidade_total', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em uso'), ('MANUTENCAO', 'Em manutenção')], default='DISPONIVEL', max_length=20)),
                ('em_uso_por', models.ForeignKey(blank=True, help_text='Membro que está atualmente com o material', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membro')),
                ('nucleo_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.nucleo')),
            ],
        ),
    ]
