# Generated by Django 5.2 on 2025-07-13 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='em_uso_por',
        ),
        migrations.CreateModel(
            name='HistoricoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao_prevista', models.DateField()),
                ('data_devolucao_real', models.DateTimeField(blank=True, help_text='Preenchido quando o material é devolvido', null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='members.material')),
                ('membro', models.ForeignKey(help_text='Membro que retirou o material', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membro')),
            ],
            options={
                'ordering': ['-data_retirada'],
            },
        ),
    ]
