# Generated by Django 5.2 on 2025-07-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_membronucleo_options_alter_nucleo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('RG', 'Reunião Geral'), ('PC', 'Ponto de controle')], default='PC', max_length=2)),
                ('ata', models.FileField(blank=True, null=True, upload_to='atas/')),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membro')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.reuniao')),
            ],
            options={
                'unique_together': {('membro', 'reuniao')},
            },
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_justificativa', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status_analise', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=20)),
                ('feedback_analise', models.TextField(blank=True, help_text='Feedback do Núcleo X sobre a análise.', null=True)),
                ('falta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.falta')),
            ],
        ),
    ]
