# Generated by Django 5.2 on 2025-07-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_material_em_uso_por_historicoreserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_material', models.CharField(max_length=150)),
                ('justificativa', models.TextField(help_text='Explique por que este material é necessário.')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('link_referencia', models.URLField(blank=True, help_text='Link de onde comprar o produto (opcional)', max_length=500, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('COMPRADO', 'Comprado')], default='PENDENTE', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('feedback_gestao', models.TextField(blank=True, help_text='Feedback do gestor ao analisar o pedido.', null=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membro')),
            ],
            options={
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
