# Generated by Django 5.2 on 2025-07-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_solicitacaomaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleo',
            name='categoria',
            field=models.CharField(choices=[('TECNICO', 'Técnico'), ('GESTAO', 'Gestão')], max_length=8),
        ),
    ]
